openapi: 3.1.0
info:
  title: Coolify
  version: '0.1'
paths:
  /deployments:
    get:
      tags:
        - Deployments
      summary: List
      description: List currently running deployments
      operationId: list-deployments
      responses:
        '200':
          description: Get all currently running deployments.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApplicationDeploymentQueue'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerAuth: []
  /deployments/{uuid}:
    get:
      tags:
        - Deployments
      summary: Get
      description: Get deployment by UUID.
      operationId: get-deployment-by-uuid
      parameters:
        - name: uuid
          in: path
          description: Deployment UUID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get deployment by UUID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationDeploymentQueue'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
      security:
        - bearerAuth: []
  /deploy:
    get:
      tags:
        - Deployments
      summary: Deploy
      description: Deploy by tag or uuid. `Post` request also accepted.
      operationId: deploy-by-tag-or-uuid
      parameters:
        - name: tag
          in: query
          description: Tag name(s). Comma separated list is also accepted.
          schema:
            type: string
        - name: uuid
          in: query
          description: Resource UUID(s). Comma separated list is also accepted.
          schema:
            type: string
        - name: force
          in: query
          description: Force rebuild (without cache)
          schema:
            type: boolean
      responses:
        '200':
          description: Get deployment(s) UUID's
          content:
            application/json:
              schema:
                properties:
                  deployments:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        resource_uuid:
                          type: string
                        deployment_uuid:
                          type: string
                      type: object
                type: object
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerAuth: []
