openapi: 3.1.0
info:
  title: Coolify
  version: '0.1'
paths:
  /security/keys:
    get:
      tags:
        - Private Keys
      summary: List
      description: List all private keys.
      operationId: list-private-keys
      responses:
        '200':
          description: Get all private keys.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrivateKey'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerAuth: []
    post:
      tags:
        - Private Keys
      summary: Create
      description: Create a new private key.
      operationId: create-private-key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - private_key
              properties:
                name:
                  type: string
                description:
                  type: string
                private_key:
                  type: string
              type: object
              additionalProperties: false
      responses:
        '201':
          description: The created private key's UUID.
          content:
            application/json:
              schema:
                properties:
                  uuid:
                    type: string
                type: object
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerAuth: []
    patch:
      tags:
        - Private Keys
      summary: Update
      description: Update a private key.
      operationId: update-private-key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - private_key
              properties:
                name:
                  type: string
                description:
                  type: string
                private_key:
                  type: string
              type: object
              additionalProperties: false
      responses:
        '201':
          description: The updated private key's UUID.
          content:
            application/json:
              schema:
                properties:
                  uuid:
                    type: string
                type: object
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerAuth: []
  /security/keys/{uuid}:
    get:
      tags:
        - Private Keys
      summary: Get
      description: Get key by UUID.
      operationId: get-private-key-by-uuid
      parameters:
        - name: uuid
          in: path
          description: Private Key UUID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get all private keys.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateKey'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          description: Private Key not found.
      security:
        - bearerAuth: []
    delete:
      tags:
        - Private Keys
      summary: Delete
      description: Delete a private key.
      operationId: delete-private-key-by-uuid
      parameters:
        - name: uuid
          in: path
          description: Private Key UUID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Private Key deleted.
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: Private Key deleted.
                type: object
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          description: Private Key not found.
      security:
        - bearerAuth: []
