openapi: 3.1.0
info:
  title: Coolify
  version: '0.1'
paths:
  /version:
    get:
      summary: Version
      description: Get Coolify version.
      operationId: version
      responses:
        '200':
          description: Returns the version of the application
          content:
            application/json:
              schema:
                type: string
              example: v4.0.0
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
      security:
        - bearerAuth: []
  /enable:
    get:
      summary: Enable API
      description: Enable API (only with root permissions).
      operationId: enable-api
      responses:
        '200':
          description: Enable API.
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: API enabled.
                type: object
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: You are not allowed to enable the API.
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: You are not allowed to enable the API.
                type: object
      security:
        - bearerAuth: []
  /disable:
    get:
      summary: Disable API
      description: Disable API (only with root permissions).
      operationId: disable-api
      responses:
        '200':
          description: Disable API.
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: API disabled.
                type: object
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: You are not allowed to disable the API.
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: You are not allowed to disable the API.
                type: object
      security:
        - bearerAuth: []
  /health:
    get:
      summary: Healthcheck
      description: Healthcheck endpoint.
      operationId: healthcheck
      responses:
        '200':
          description: Healthcheck endpoint.
          content:
            application/json:
              schema:
                type: string
              example: OK
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
